### ISSUE TITLE
Is it possible to load a texture on them?

### ISSUE THREAD

**Issue by paulmelero** [pailhead/three-rounded-box#1]
I was trying something like

```
import textureImage from 'correctPath/whatever.jpg';
var mesh = new THREE.Mesh( new RoundedBoxGeometry( ... ) );
var textureLoader = new THREE.TextureLoader();
textureLoader.load( textureImage, function ( texture ) {
    mesh.material = new THREE.MeshBasicMaterial({
        map: texture
    } );
    mesh.material.map.repeat.set( 2, 2 );
} );
```

But only thing I was getting was a plain color. No matter what image was loaded...

**Comment by pailhead** [comment]
It doesn't generate uv coordinates as is. I'm not sure what the best solution would be nor how to handle the corners. It's possible to iterate through the vertices and project them onto six planes, it may not be trivial though to find the splits for the different uvs that would need to happen on the same edge / normal.
